const systems = [
  { runs: true, sme: "SME00410", manu: "Philips", mod: "CT" },
  { runs: true, sme: "SME00891", manu: "Siemens", mod: "CT" },
  { runs: true, sme: "SME01068", manu: "Siemens", mod: "CT" },
  { runs: true, sme: "SME01074", manu: "Siemens", mod: "CT" },
  { runs: true, sme: "SME01094", manu: "Siemens", mod: "CT" },
  { runs: true, sme: "SME01116", manu: "Siemens", mod: "CT" },
  { runs: true, sme: "SME01435", manu: "GE", mod: "CT" },
  { runs: true, sme: "SME00897", manu: "GE", mod: "CT" },
  { runs: false, sme: "SME01098", manu: "Siemens", mod: "PET/CV", note: "Needs rpp work" },
  { runs: false, sme: "SME00508", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME00509", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME00510", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME00511", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01387", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01388", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01389", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01391", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01392", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01393", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01394", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01396", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME01397", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME02531", manu: "Philips", mod: "CV/IR" },
  { runs: false, sme: "SME08325", manu: "Philips", mod: "CV/IR" },
];
